"""create_inventory_state_processed_actions

Revision ID: 970ef416daed
Revises: e7f1d57c0207
Create Date: 2026-06-27 00:47:24.649503
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970ef416daed'
down_revision: Union[str, None] = 'e7f1d57c0207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('ospos_sale_id', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_state_order_id'), 'inventory_state', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventory_state_sku'), 'inventory_state', ['sku'], unique=False)
    op.create_index(op.f('ix_inventory_state_source_event_id'), 'inventory_state', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_inventory_state_state'), 'inventory_state', ['state'], unique=False)
    op.create_table('processed_actions',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('target_system', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('request_summary', sa.Text(), nullable=True),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'target_system')
    )
    op.create_index(op.f('ix_processed_actions_sku'), 'processed_actions', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_actions_sku'), table_name='processed_actions')
    op.drop_table('processed_actions')
    op.drop_index(op.f('ix_inventory_state_state'), table_name='inventory_state')
    op.drop_index(op.f('ix_inventory_state_source_event_id'), table_name='inventory_state')
    op.drop_index(op.f('ix_inventory_state_sku'), table_name='inventory_state')
    op.drop_index(op.f('ix_inventory_state_order_id'), table_name='inventory_state')
    op.drop_table('inventory_state')
    # ### end Alembic commands ###
