"""initial_schema

Revision ID: e587fac1efa1
Revises: 
Create Date: 2026-05-26 20:21:37.292782
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e587fac1efa1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_fee_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('fee_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_state',
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('stock_buffer', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('channel')
    )
    op.create_table('channel_variant_mapping',
    sa.Column('variant_sku', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('external_var_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('variant_sku', 'channel')
    )
    op.create_table('event_store',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('ospos_synced', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_store_channel', 'event_store', ['channel'], unique=False)
    op.create_index('ix_event_store_sku', 'event_store', ['sku'], unique=False)
    op.create_index('ix_event_store_state', 'event_store', ['state'], unique=False)
    op.create_table('onboarding_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_images_session_id'), 'onboarding_images', ['session_id'], unique=False)
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('images_processed', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_sessions_sku'), 'onboarding_sessions', ['sku'], unique=False)
    op.create_table('product_mapping',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('ospos_id', sa.Integer(), nullable=False),
    sa.Column('has_variants', sa.Boolean(), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('channel_product_mapping',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['product_mapping.sku'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sku', 'channel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_product_mapping')
    op.drop_table('product_mapping')
    op.drop_index(op.f('ix_onboarding_sessions_sku'), table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_images_session_id'), table_name='onboarding_images')
    op.drop_table('onboarding_images')
    op.drop_index('ix_event_store_state', table_name='event_store')
    op.drop_index('ix_event_store_sku', table_name='event_store')
    op.drop_index('ix_event_store_channel', table_name='event_store')
    op.drop_table('event_store')
    op.drop_table('channel_variant_mapping')
    op.drop_table('channel_state')
    op.drop_table('channel_fee_config')
    # ### end Alembic commands ###
